import { useEffect, useRef, useState } from 'react'
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  IconButton,
  Stack,
  Typography,
} from '@mui/material'
import ContentCopyIcon from '@mui/icons-material/ContentCopy'
import LogoutOutlinedIcon from '@mui/icons-material/LogoutOutlined'
import { useNavigate } from 'react-router-dom'
import { useSnackbar } from 'notistack'
import { useHousehold, useGenerateInvite, useLeaveHousehold } from '@/features/auth/useHousehold'
import { SETUP_DISMISSED_KEY } from '@/lib/storageKeys'

/** Settings sub-page for managing the household: shows members and the partner invite code. */
export function HouseholdPage() {
  const { data, isLoading } = useHousehold()
  const generateInvite = useGenerateInvite()
  // The mutation result is the source of truth for a freshly generated code, so
  // there's no local state to keep in sync.
  const { mutate: runGenerate, isPending, data: generatedCode } = generateInvite
  const leaveHousehold = useLeaveHousehold()
  const navigate = useNavigate()
  const { enqueueSnackbar } = useSnackbar()

  const [confirmLeave, setConfirmLeave] = useState(false)

  const household = data?.household
  const members = data?.members ?? []
  const hasPartner = members.length >= 2

  const handleLeave = async () => {
    if (!household) return
    try {
      await leaveHousehold.mutateAsync(household.id)
      // Re-surface the home "Get started" checklist for the next household.
      localStorage.removeItem(SETUP_DISMISSED_KEY)
      setConfirmLeave(false)
      enqueueSnackbar('You left the household', { variant: 'success' })
      navigate('/onboarding', { replace: true })
    } catch (error) {
      enqueueSnackbar(error instanceof Error ? error.message : 'Could not leave household', {
        variant: 'error',
      })
    }
  }

  // A freshly generated code takes precedence over the stored one.
  const code = generatedCode ?? household?.invite_code ?? null

  const handleGenerate = () => {
    if (!household) return
    runGenerate(household.id, {
      onError: () => enqueueSnackbar('Could not generate an invite code', { variant: 'error' }),
    })
  }

  // The stored invite code expires after 48h. When the page opens with a
  // missing or expired code, regenerate it automatically so the user is never
  // handed a dead code to share. (Date.now() is read here, in the effect,
  // rather than during render to keep render pure.)
  const autoGenerated = useRef(false)
  useEffect(() => {
    if (autoGenerated.current || !household || hasPartner) return
    const expiresAt = household.invite_expires_at
    const stale =
      !household.invite_code || !expiresAt || new Date(expiresAt).getTime() <= Date.now()
    if (!stale) return
    autoGenerated.current = true
    runGenerate(household.id, {
      onError: () => enqueueSnackbar('Could not generate an invite code', { variant: 'error' }),
    })
  }, [household, hasPartner, runGenerate, enqueueSnackbar])

  const handleCopy = async () => {
    if (!code) return
    try {
      await navigator.clipboard.writeText(code)
      enqueueSnackbar('Invite code copied', { variant: 'success' })
    } catch {
      enqueueSnackbar('Could not copy', { variant: 'warning' })
    }
  }

  return (
    <Box sx={{ p: { xs: 2, md: 3 }, pb: { xs: 12, md: 4 }, display: 'flex', flexDirection: 'column', gap: 2 }}>
      <Typography variant="titleLarge">Household</Typography>

      {isLoading ? (
        <CircularProgress size={24} />
      ) : (
        <>
          <Card>
            <CardContent>
              <Typography variant="titleMedium" sx={{ mb: 1 }}>
                {household?.name ?? 'Our Home'}
              </Typography>
              <Typography variant="bodyMedium" color="text.secondary">
                {members.map((member) => member.display_name).join(' & ')}
              </Typography>
            </CardContent>
          </Card>

          <Card>
            <CardContent>
              {hasPartner ? (
                <Alert severity="success">Your partner has joined this household.</Alert>
              ) : (
                <Stack spacing={2} sx={{ alignItems: 'flex-start' }}>
                  <Typography variant="bodyMedium" color="text.secondary">
                    Share this 6-digit code so your partner can join. Codes expire after 48 hours.
                  </Typography>
                  {code && !isPending && (
                    <Stack direction="row" spacing={1} sx={{ alignItems: 'center' }}>
                      <Typography variant="headlineMedium" sx={{ letterSpacing: '0.25em' }}>
                        {code}
                      </Typography>
                      <IconButton onClick={handleCopy} aria-label="Copy invite code">
                        <ContentCopyIcon />
                      </IconButton>
                    </Stack>
                  )}
                  <Button variant="contained" onClick={handleGenerate} disabled={isPending}>
                    {isPending ? (
                      <CircularProgress size={20} color="inherit" />
                    ) : code ? (
                      'Regenerate code'
                    ) : (
                      'Generate invite code'
                    )}
                  </Button>
                </Stack>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardContent>
              <Typography variant="titleMedium" sx={{ mb: 1 }}>
                Leave household
              </Typography>
              <Typography variant="bodyMedium" color="text.secondary" sx={{ mb: 1.5 }}>
                Exit this household to create or join a different one with an invite code.
              </Typography>
              <Button
                variant="outlined"
                color="error"
                startIcon={<LogoutOutlinedIcon />}
                onClick={() => setConfirmLeave(true)}
              >
                Leave household
              </Button>
            </CardContent>
          </Card>
        </>
      )}

      <Dialog open={confirmLeave} onClose={() => !leaveHousehold.isPending && setConfirmLeave(false)}>
        <DialogTitle>Leave this household?</DialogTitle>
        <DialogContent>
          <DialogContentText>
            {hasPartner
              ? 'You will be removed from this household and your partner will keep it. Your expenses stay in the shared ledger. You can then create or join another household.'
              : "You're the only member, so this household and all its data will be deleted. You can then create or join another household."}
          </DialogContentText>
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 2 }}>
          <Button onClick={() => setConfirmLeave(false)} disabled={leaveHousehold.isPending}>
            Cancel
          </Button>
          <Button
            color="error"
            variant="contained"
            onClick={() => void handleLeave()}
            disabled={leaveHousehold.isPending}
          >
            {leaveHousehold.isPending ? <CircularProgress size={20} color="inherit" /> : 'Leave'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
